import { Footer } from './Footer'
import './globals.css'
import Navbar from './Navbar'
import Providers from './providers'

export const metadata = {
  title: 'Flashcard App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          <main className='max-w-[1200px] mx-auto my-10 p-2'>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
