import { Footer } from './Footer'
import './globals.css'
import { Navbar } from './Navbar'
import Providers from './providers'

export const metadata = {
  title: 'Flashcard App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
